# docker-compose.yml for react + django + postgresql based project
version: "3.9"
services:
  db:
    image: postgres:alpine3.18
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbdev
      - POSTGRES_USER=userdbdev
      - POSTGRES_PASSWORD=userdbdevpasword
  backend:
    build:
      context: ./backend
      args:
        - DEV=true
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - web-data:/app/media
    environment:
      - DB_HOST=db
      - DB_NAME=dbdev
      - DB_USER=userdbdev
      - DB_PASS=userdbdevpasword
      - DEBUGING=True
    depends_on:
      - db
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm start"
    depends_on:
      - backend
    ports:
      - 3000:3000
volumes:
  db-data:
  web-data:
  front-data:
